apiVersion: apps/v1
kind: Deployment
metadata:
  name: authbackend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: authbackend
  template:
    metadata:
      labels:
        app: authbackend
    spec:
      containers:
      - name: authbackend
        image: arehmanse/authbackend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: authbackend-service
spec:
  selector:
    app: authbackend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
